export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

if command -v wt >/dev/null 2>&1; then eval "$(command wt config shell init bash)"; fi

# himalaya aliases
alias hil='himalaya envelope list'
function garchive() { himalaya message move "$1" "[Gmail]/All Mail"; }
